config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only: %i[index]
  resources :accounts, only: %i[index] do
    member do
      post :transfer
    end
  end
end

app/models/account.rb
# Entity that represents a bank account
class Account < ApplicationRecord
  belongs_to :user

  has_many :account_activities

  validates :user, presence: true

  def balance
    credits = account_activities.credit.sum(:amount)
    debits = account_activities.debit.sum(:amount)

    credits - debits
  end
end

app/models/account_activity.rb
# Entity to register credits and debits
class AccountActivity < ApplicationRecord
  belongs_to :account

  enum activity_type: %i[credit debit]

  validates :account, :activity_type, presence: true
  validates :amount, numericality: { greater_than: 0 }, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_one :account

  validates :email, presence: true
end

app/controllers/accounts_controller.rb
# Accounts controller
class AccountsController < ApplicationController
  def index
    @account = Account.find_by(user_id: current_user.id)
  end

  def transfer; end
end

app/controllers/application_controller.rb
# Application Controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# Home controller
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      Your current account balance:
    </div>

    <div class="col-md">
      <%= number_to_currency((@account&.balance || 0), unit: "R$",
                                                       separator: ",",
                                                       delimiter: "") %>
    </div>
  </div>

  <%= form_for :account, url: transfer_account_path(@account&.id), method: :post do |f| %>
    <div class="row">
      <div class="col-md">
        Transfer money to another account:
      </div>

      <div class="col-md">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">$</span>
          </div>
          <%= f.text_field :amount, class: 'form-control' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div>
</div>

app/views/layouts/_user_navigation.html.erb
<ul class="nav justify-content-center">
  <li class="nav-item">
    <%= link_to 'Users', users_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Accounts', accounts_path, class: 'nav-link' %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exwallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'layouts/user_navigation' %>

    <%= yield %>
  </body>
</html>